### ISSUE TITLE
Is This Working?

### ISSUE THREAD

**Issue by jyuuren** [feyraftsl/android_device_xiaomi_agate-twrp#1]
Is this device tree working on Android 13?

**Comment by feyraftsl** [comment]
> Is this device tree working on Android 13

yes

**Comment by jyuuren** [comment]
I tried building OrangeFox using this tree today and it works without issues! Thank you so much.

**Comment by feyraftsl** [comment]
> I tried building OrangeFox using this tree today and it works without issues! Thank you so much.

🥰
